import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";
import {Toaster} from "@/components/ui/toaster";
import {AuthProvider} from "@/context/AuthContext";

const monts = Montserrat({
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={monts.className}>
      <body>
              <Navigation/>
              <AuthProvider>
                  <div className="xl:container mx-auto px-[26px] xl:px-0 mt-[70px]">
                      {children}
                  </div>
                  <Footer/>
                  <Toaster />
              </AuthProvider>

      </body>
    </html>
  );
}
